name: Deploy to ECR

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag image to Amazon ECR
      env:
        ECR_REGISTRY: "public.ecr.aws/t6p6b9i9"
        ECR_REPOSITORY: lidor-web-project
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

    - name: Push Amazon ECR
      if: github.event_name != 'pull_request'
      env:
        ECR_REGISTRY: "public.ecr.aws/t6p6b9i9"
        ECR_REPOSITORY: lidor-web-project
        IMAGE_TAG: latest
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


